# Docker specific configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA Configuration
spring.jpa.show-sql=false

# Auth Service
auth.service.url=${AUTH_SERVICE_URL}
auth.service.credentials.endpoint=${AUTH_SERVICE_CREDENTIALS_ENDPOINT}
auth.service.credentials=${AUTH_SERVICE_CREDENTIALS}
auth.service.authenticate.service=${AUTH_SERVICE_AUTHENTICATE_SERVICE}
auth.service.retry.max-attempts=${AUTH_SERVICE_RETRY_MAX_ATTEMPTS:3}
auth.service.retry.initial-delay-ms=${AUTH_SERVICE_RETRY_INITIAL_DELAY_MS:300}
auth.service.retry.max-delay-ms=${AUTH_SERVICE_RETRY_MAX_DELAY_MS:2000}
auth.service.retry.multiplier=${AUTH_SERVICE_RETRY_MULTIPLIER:2.0}

# Notification Service
notification.service.url=${NOTIFICATION_SERVICE_URL}

