# Docker specific configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA Configuration
spring.jpa.show-sql=false

# Auth Service
auth.service.url=${AUTH_SERVICE_URL}
auth.service.credentials.endpoint=${AUTH_SERVICE_CREDENTIALS_ENDPOINT}
auth.service.credentials=${AUTH_SERVICE_CREDENTIALS}
auth.service.authenticate.service=${AUTH_SERVICE_AUTHENTICATE_SERVICE}
